version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: dsadsf0/todo_server
    ports:
      - "3001:3001"
    environment:
      - PG_DB=todos
      - PG_USER=admin
      - PG_PASSWORD=root
      - PG_HOST=todo_db
    depends_on:
      - todo_db

  todo_db:
    container_name: todo_db
    image: postgres:15.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todos
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root
    volumes:
      - todo_db_data:/var/lib/postgresql/data

volumes:
  todo_db_data: {}